const Map<String, String> enUS = {
  "select_language": "Select Language",
  "please_choose_your_preferred_language_to_continue":
      "Please choose your preferred language to continue",
  "english": "English",
  "arabic": "Arabic",
  "continue": "Continue",
  "welcome_back": "Welcome Back",
  "enter_your_credentials_to_login_into_the_technician_app":
      "Enter your credentials to Login into the technician App",
  "employee_id": "Employee ID",
  "enter_your_employee_id": "Enter your Employee ID",
  "enter_your_password": "Enter your password",
  "password": "Password",
  "forgot_password": "Forgot Password?",
  "login": "Login",
  "employee_id_is_required": "Employee ID is required",
  "password_is_required": "Password is required",
  "invalid_credentials": "Invalid credentials",
  "invalid_request": "Invalid request",
  "account_verification": "Account Verification",
  "enter_otp": "Enter OTP",
  "resend_otp": "Resend OTP",
  "home": "Home",
  "history": "History",
  "profile": "Profile",
  "failed_to_load_pending_bookings": "Failed to load pending bookings",
  "booking_assigned": "Booking assigned",
  "failed_to_accept_booking": "Failed to accept booking",
  "booking_rejected": "Booking rejected",
  "failed_to_reject_booking": "Failed to reject booking",
  "employee_not_found": "Employee not found",
  "employee_id_not_found": "Employee ID not found",
  "failed_to_load_booking_history": "Failed to load booking history",
  "new_task_assigned": "New Task Assigned",
  "notifications": "Notifications",
  "clear": "CLEAR",
  "yesterday": "YESTERDAY",
  "premium_wash_bay3": "Premium Wash at 5th Ave Mall - Bay 3",
  "message_from_admin": "Message from Admin",
  "check_inventory_soap":
      "Please check the inventory for soap supplies before EOD.",
  "task_updated": "Task Updated",
  "location_moved_sector4": "Location moved to Sector 4 South Entrance",
  "reminder_upcoming_task": "Reminder: Upcoming Task",
  "scheduled_start_in_15_mins": "Scheduled start in 15 minutes",
  "system_update": "System Update",
  "version_240_live": "Version 2.4.0 is now live. Check the new map features.",
  "commission_paid": "Commission Paid",
  "commission_paid_msg":
      "Your earnings for the previous week have been processed.",
  "avg_rating": "Avg Rating",
  "jobs_done": "Jobs Done",
  "on_time": "On-Time",
  "todays_summary": "Today's Summary",
  "total_jobs": "TOTAL JOBS",
  "earnings": "EARNINGS",
  "pending": "PENDING",
  "completed": "COMPLETED",
  "pending_tasks": "Pending Tasks",
  "are_you_sure_you_want_to_reject_this_booking":
      "Are you sure you want to reject this booking?",
  "reject_booking": "Reject Booking",
  "yes_reject": "Yes, Reject",
  "no": "No",
  "reject": "Reject",
  "accept": "Accept",
  "booking_history": "Booking History",
  "search_by_name_service_or_booking_id":
      "Search by name, service or booking id",
  "no_history_found": "No history found",
  "amount": "Amount",
  "view_details": "View Details",
  "my_profile": "My Profile",
  "technician": "Technician",
  "change_language": "Change Language",
  "change_password": "Change Password",
  "logout": "Logout",
  "are_you_sure_you_want_to_logout": "Are you sure you want to logout?",
  "booking_details": "Booking Details",
  "before": "BEFORE",
  "before_wash_videos": "Before Wash - Videos",
  "after_wash": "After Wash",
  "after": "AFTER",
  "after_wash_videos": "After Wash - Videos",
  "job_status": "Job Status",
  "vehicle_detail": "Vehicle Detail",
  "no_images_available": "No images available",
  "failed_to_load": "Failed to load",
  "image_load_error_for": "Image load error for",
  "no_videos_available": "No videos available",
  "service_summary": "Service Summary",
  "service": "Service",
  "status": "Status",
  "current_password": "Current Password",
  "new_password": "New Password",
  "confirm_password": "Confirm Password",
  "update_password": "Update Password",
  "location": "Location",
  "all_fields_are_required": "All fields are required",
  "new_password_must_be_at_least_6_characters":
      "New password must be at least 6 characters",
  "new_password_must_be_different_from_current_password":
      "New password must be different from current password",
  "passwords_do_not_match": "Passwords do not match",
  "something_went_wrong_please_try_again":
      "Something went wrong. Please try again.",
  "todays_tasks": "Today's Tasks",
  "car_inspection": "Car Inspection",
  "service_package": "Service Package",
  "premium_interior_exterior": "Premium Interior & Exterior",
  "before_wash": "Before Wash",
  "capture_existing_damage_or_dirt_levels_before_starting":
      "Capture existing damage or dirt levels before starting.",
  "show_completed_work_to_verify_quality":
      "Show completed work to verify quality.",
  "camera_or_gallery": "Camera or Gallery",
  "add_photo": "Add Photo",
  "camera": "Camera",
  "gallery": "Gallery",
  "address_line1": "123 Main Street",
  "address_line2": "San Francisco, CA 94103",
  "supported_by_gpay_phonepe_paytm": "Supported by GPay, PhonePe, Paytm",
  "record_video": "Record Video",
  "pick_video": "Pick Video",
  "please_upload_before_after_images": "Please upload before & after images",
  "failed_to_upload_before_images": "Failed to upload before images",
  "failed_to_upload_after_images": "Failed to upload after images",
  "before_images_error": "Before images:",
  "after_images_error": "After images:",
  "images_uploaded_successfully": "Images uploaded successfully!",
  "no_tasks_available": "No tasks available.",
  "no_pending_tasks_available": "No pending tasks available.",
  "start_work": "Start Work",
  "something_went_wrong": "Something went wrong",
  "customer_location": "Customer Location",
  "navigate": "Navigate",
  "ive_arrived": "I've Arrived",
  "arrived_confirmed": "Arrived confirmed",
  "failed_to_mark_arrival": "Failed to mark arrival",
  "payment": "Payment",
  "customer": "Customer",
  "amount_to_collect": "Amount to Collect",
  "payment_completed": "Payment Completed",
  "payment_pending": "Payment Pending",
  "upi_payment": "UPI Payment",
  "scan_qr_to_pay": "Scan QR to pay",
  "upi_id": "UPI ID",
  "cash_received": "Cash Received",
  "proceed_to_summary": "Proceed to Summary",
  "please_collect_payment_first": "Please collect payment first",
  "failed_to_complete_wash": "Failed to complete wash",
  "job_completed": "Job Completed!",
  "the_service_has_been_successfully_completed":
      "The service has been successfully completed.",
  "job_summary": "JOB SUMMARY",
  "vehicle": "Vehicle",
  "start_time": "START TIME",
  "end_time": "END TIME",
  "total_amount": "Total Amount",
  "back_to_dashboard": "Back to Dashboard",
  "task_details": "Task Details",
  "vehicle_service_details": "Vehicle & Service Details",
  "get_directions": "Get Directions",
  "total_price": "Total Price",
  "start_task": "Start Task",
  "work_started": "Work started!",
  "failed_to_start_work": "Failed to start work",
};
