const Map<String, String> arSA = {
  "select_language": "اختر اللغة",
  "please_choose_your_preferred_language_to_continue":
      "يرجى اختيار لغتك المفضلة للمتابعة",
  "english": "الإنجليزية",
  "arabic": "العربية",
  "continue": "متابعة",
  "welcome_back": "مرحبًا بعودتك",
  "enter_your_credentials_to_login_into_the_technician_app":
      "أدخل بيانات الاعتماد لتسجيل الدخول إلى تطبيق الفني",
  "employee_id": "معرّف الموظف",
  "enter_your_employee_id": "أدخل معرّف الموظف",
  "enter_your_password": "أدخل كلمة المرور",
  "password": "كلمة المرور",
  "forgot_password": "هل نسيت كلمة المرور؟",
  "login": "تسجيل الدخول",
  "employee_id_is_required": "معرّف الموظف مطلوب",
  "password_is_required": "كلمة المرور مطلوبة",
  "account_verification": "التحقق من الحساب",
  "enter_otp": "أدخل رمز OTP",
  "resend_otp": "إعادة إرسال OTP",
  "home": "الرئيسية",
  "history": "السجل",
  "profile": "الملف الشخصي",
  "failed_to_load_pending_bookings": "فشل تحميل الحجوزات المعلقة",
  "booking_assigned": "تم تعيين الحجز",
  "failed_to_accept_booking": "فشل قبول الحجز",
  "booking_rejected": "تم رفض الحجز",
  "failed_to_reject_booking": "فشل رفض الحجز",
  "employee_not_found": "الموظف غير موجود",
  "failed_to_load_booking_history": "فشل تحميل سجل الحجوزات",
  "new_task_assigned": "تم تعيين مهمة جديدة",
  "notifications": "الإشعارات",
  "clear": "مسح",
  "yesterday": "أمس",
  "premium_wash_bay3": "غسيل مميز في 5th Ave Mall - Bay 3",
  "message_from_admin": "رسالة من المشرف",
  "check_inventory_soap": "يرجى التحقق من مخزون الصابون قبل نهاية اليوم.",
  "task_updated": "تحديث المهمة",
  "location_moved_sector4": "تم نقل الموقع إلى القطاع 4 المدخل الجنوبي",
  "reminder_upcoming_task": "تذكير: مهمة قادمة",
  "scheduled_start_in_15_mins": "بدء مجدول خلال 15 دقيقة",
  "system_update": "تحديث النظام",
  "version_240_live": "الإصدار 2.4.0 متاح الآن. تحقق من ميزات الخريطة الجديدة.",
  "commission_paid": "تم دفع العمولة",
  "commission_paid_msg": "تمت معالجة أرباحك للأسبوع السابق.",
  "avg_rating": "متوسط التقييم",
  "jobs_done": "المهام المكتملة",
  "on_time": "في الوقت المحدد",
  "todays_summary": "ملخص اليوم",
  "total_jobs": "إجمالي المهام",
  "earnings": "الأرباح",
  "pending": "قيد الانتظار",
  "completed": "مكتمل",
  "pending_tasks": "المهام المعلقة",
  "are_you_sure_you_want_to_reject_this_booking":
      "هل أنت متأكد أنك تريد رفض هذا الحجز؟",
  "reject_booking": "رفض الحجز",
  "yes_reject": "نعم، رفض",
  "no": "لا",
  "reject": "رفض",
  "accept": "قبول",
  "booking_history": "سجل الحجوزات",
  "search_by_name_service_or_booking_id": "ابحث بالاسم أو الخدمة أو رقم الحجز",
  "no_history_found": "لم يتم العثور على سجل",
  "amount": "المبلغ",
  "view_details": "عرض التفاصيل",
  "my_profile": "ملفي الشخصي",
  "technician": "الفني",
  "change_language": "تغيير اللغة",
  "change_password": "تغيير كلمة المرور",
  "logout": "تسجيل الخروج",
  "are_you_sure_you_want_to_logout": "هل أنت متأكد أنك تريد تسجيل الخروج؟",
  "booking_details": "تفاصيل الحجز",
  "before": "قبل",
  "before_wash_videos": "فيديوهات قبل الغسيل",
  "after_wash": "بعد الغسيل",
  "after": "بعد",
  "after_wash_videos": "فيديوهات بعد الغسيل",
  "job_status": "حالة المهمة",
  "vehicle_detail": "تفاصيل المركبة",
  "no_images_available": "لا توجد صور متاحة",
  "failed_to_load": "فشل التحميل",
  "image_load_error_for": "خطأ تحميل الصورة لـ",
  "no_videos_available": "لا توجد فيديوهات متاحة",
  "service_summary": "ملخص الخدمة",
  "service": "الخدمة",
  "status": "الحالة",
  "current_password": "كلمة المرور الحالية",
  "new_password": "كلمة المرور الجديدة",
  "confirm_password": "تأكيد كلمة المرور",
  "update_password": "تحديث كلمة المرور",
  "location": "الموقع",
  "all_fields_are_required": "جميع الحقول مطلوبة",
  "new_password_must_be_at_least_6_characters":
      "يجب أن تتكون كلمة المرور الجديدة من 6 أحرف على الأقل",
  "new_password_must_be_different_from_current_password":
      "يجب أن تكون كلمة المرور الجديدة مختلفة عن الحالية",
  "passwords_do_not_match": "كلمات المرور غير متطابقة",
  "something_went_wrong_please_try_again":
      "حدث خطأ ما. يرجى المحاولة مرة أخرى.",
  "todays_tasks": "مهام اليوم",
  "car_inspection": "فحص السيارة",
  "service_package": "باقة الخدمة",
  "premium_interior_exterior": "تنظيف داخلي وخارجي مميز",
  "before_wash": "قبل الغسيل",
  "capture_existing_damage_or_dirt_levels_before_starting":
      "قم بتوثيق الأضرار أو مستوى الأوساخ قبل البدء.",
  "show_completed_work_to_verify_quality":
      "عرض العمل المكتمل للتحقق من الجودة.",
  "camera_or_gallery": "الكاميرا أو المعرض",
  "add_photo": "إضافة صورة",
  "camera": "الكاميرا",
  "gallery": "المعرض",
  "address_line1": "123 Main Street",
  "address_line2": "San Francisco, CA 94103",
  "supported_by_gpay_phonepe_paytm": "مدعوم من GPay وPhonePe وPaytm",
  "record_video": "تسجيل فيديو",
  "pick_video": "اختيار فيديو",
  "please_upload_before_after_images": "يرجى تحميل صور قبل وبعد",
  "failed_to_upload_before_images": "فشل تحميل صور قبل",
  "failed_to_upload_after_images": "فشل تحميل صور بعد",
  "images_uploaded_successfully": "تم تحميل الصور بنجاح!",
  "no_tasks_available": "لا توجد مهام.",
  "no_pending_tasks_available": "لا توجد مهام معلقة.",
  "start_work": "ابدأ العمل",
  "something_went_wrong": "حدث خطأ ما",
  "customer_location": "موقع العميل",
  "navigate": "تنقل",
  "ive_arrived": "لقد وصلت",
  "arrived_confirmed": "تم تأكيد الوصول",
  "failed_to_mark_arrival": "فشل تسجيل الوصول",
  "payment": "الدفع",
  "customer": "العميل",
  "amount_to_collect": "المبلغ المطلوب تحصيله",
  "payment_completed": "اكتمل الدفع",
  "payment_pending": "الدفع معلق",
  "upi_payment": "دفع UPI",
  "scan_qr_to_pay": "امسح رمز QR للدفع",
  "upi_id": "معرّف UPI",
  "cash_received": "تم استلام النقد",
  "proceed_to_summary": "المتابعة إلى الملخص",
  "please_collect_payment_first": "يرجى تحصيل الدفع أولاً",
  "failed_to_complete_wash": "فشل إكمال الغسيل",
  "job_completed": "تم إنجاز المهمة!",
  "the_service_has_been_successfully_completed": "تم إكمال الخدمة بنجاح.",
  "job_summary": "ملخص المهمة",
  "vehicle": "المركبة",
  "start_time": "وقت البدء",
  "end_time": "وقت الانتهاء",
  "total_amount": "المبلغ الإجمالي",
  "back_to_dashboard": "العودة إلى لوحة التحكم",
  "task_details": "تفاصيل المهمة",
  "vehicle_service_details": "تفاصيل المركبة والخدمة",
  "get_directions": "الحصول على الاتجاهات",
  "total_price": "السعر الإجمالي",
  "start_task": "بدء المهمة",
  "work_started": "تم بدء العمل!",
  "failed_to_start_work": "فشل بدء العمل",
};
